model: YOLOv9s.pt
project: project
name: name
model_dir: prject/name # only to continue from a checkpoint. mode_dir inside `train_results`. this is script specific argument.

# Training Args
data: dataset/data.yaml
epochs: 100
time: null
patience: 100
batch: 8
imgsz: 640
save: true
save_period: 5
cache: false
device: '0'
dropout: 0.0
close_mosaic: 0
