model: best.pt
train_dir: train3 # only to continue training (directories inside train_results directory) 
task: detect
mode: train
data: dataset/data.yaml
epochs: 100
time: null
patience: 5
batch: 8
imgsz: 640
save: true
save_period: 5
cache: false
device: '0'
workers: 8
pretrained: true
dropout: 0.0
half: True